Pages/Guards/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using GarageGuard.Data;
using GarageGuard.Models;
using Microsoft.AspNetCore.SignalR;
using GarageGuard.Hubs;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Authorization;
using GarageGuard.Utility;

namespace GarageGuard.Pages.Guards
{
   // [Authorize (Roles="admin")]  // страница доступна только для авторизованных пользователей
    public class IndexModel : PageModel
    {
        public static bool _awaitExchange; // переменная для уведомлении о синхронизации по которой определяем какой стиль у бегущей строки 

        public class LoggingEvents  //класс идентификаторов лога
        {
            public const int ActivationGuard = 2000;  /// нажатие кнопки влючения охраны
            public const int ActivationRelay = 3000;  /// нажатие кнопки влючения выключения реле
        }

        
        private readonly GarageGuard.Data.GarageGuardContext _context;
        private readonly ILogger _logger; //создаем журнал лога
        private readonly IHubContext<ChatHub> _chatHubContext;  //hub SingnalR
        public SD sd; // класс с ролями
        public IndexModel(GarageGuard.Data.GarageGuardContext context, ILogger<IndexModel> logger, IHubContext<ChatHub> chatHubContext)
        {
            
            _context = context;
            _logger = logger;
            _chatHubContext = chatHubContext;
        }


        public static DateTimeOffset timeGetToController;// дата и время фиксируемое при обмене данными с контроллером. 

        public IList<Guard> Guard { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            try
            {
                Guard = await _context.Guard.ToListAsync();
                //добавим лог при каждом посещении страницы

                _logger.LogInformation($"Message displayed: Открыта главаная страница: {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return Page();
            }
            catch (Exception ex)
            {
                _logger.LogError( $"Message displayed: Ошибка при открытии главной страницы:{ex.Message} {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return NotFound();
            }

        }
       
        /// <summary>
        /// Обработчик включение\выключения охраны
        /// </summary>
        public async  Task<RedirectToPageResult> OnPostActivationGuard()
        {
            try
            {
                Guard = await _context.Guard.ToListAsync();
                Guard.LastOrDefault().State = !Guard.LastOrDefault().State; // инверсия значения
               
                Guard.LastOrDefault().Status = "Ожидание обмена"; //ждем синхронизации с контроллером
               
                await _context.SaveChangesAsync();
                // // при нажатии кнопки активации охраны, отправить всем клиентам новый статус
                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "state", Guard.LastOrDefault().State);
                _awaitExchange = true;
                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "status", Guard.LastOrDefault().Status);//ждем синхронизации с контроллером
                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "statusLine", _awaitExchange);  // остановим бегущую строку);

                _logger.LogInformation(LoggingEvents.ActivationGuard, $"Message displayed: Нажата кнопка активации охраны: {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return RedirectToPage("./Index"); //вернемся на главную страницу
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.ActivationGuard, $"Message displayed: Ошибка при нажатии кнопки включения:{ex.Message} {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return RedirectToPage("./Index");//вернемся на главную страницу
            }
        }
        /// <summary>
        /// Обработчик включения реле
        /// </summary>
        /// <returns></returns>
        public async Task<RedirectToPageResult> OnPostActivationRelay()
        {
            try
            {
                Guard = await _context.Guard.ToListAsync();
                Guard.LastOrDefault().relay_1 = !Guard.LastOrDefault().relay_1; // инверсия значения

                _awaitExchange = true;
                Guard.LastOrDefault().Status = "Ожидание обмена"; //ждем синхронизации с контроллером
               
                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "status", Guard.LastOrDefault().Status);//ждем синхронизации с контроллером
               

                await _context.SaveChangesAsync();
                // // при нажатии кнопки включения реле, отправить всем клиентам новый статус
                await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "relay_1", Guard.LastOrDefault().relay_1);
                 await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "statusLine",_awaitExchange);  // остановим бегущую строку);
               // await _chatHubContext.Clients.All.SendAsync("ReceiveMessage", "status", "Ожидание обмена");  // при нажатии кнопки ожидание связи с контроллером
                _logger.LogInformation(LoggingEvents.ActivationRelay, $"Message displayed: Нажата кнопка вкл/откл реле: {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return RedirectToPage("./Index"); //вернемся на главную страницу
            }
            catch (Exception ex)
            {
                _logger.LogError(LoggingEvents.ActivationRelay, $"Message displayed: Ошибка при нажатии кнопки вкл/откл реле:{ex.Message} {DateTime.UtcNow.ToLongTimeString()}"); //Log
                return RedirectToPage("./Index");//вернемся на главную страницу
            }
        }

    }
}

Pages/Shared/_ButtonsPartial.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GarageGuard.Pages.Shared
{
    public class _ButtonsPartialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/_LoginPartial.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GarageGuard.Pages.Shared
{
    public class _LoginPartialModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Shared/_ButtonsPartial.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<div class="col-auto col-sm-auto">


    <!--Кнопка вкл\выкл охраны-->
    <form method="post">

        <button type="submit" asp-page-handler="ActivationGuard" class="badge badge-secondary"
                id="btnActivationGuard">
            Охрана
        </button>

    </form>
</div>
<div class="col-auto col-sm-auto">
    <!--Кнопка вкл\выкл реле1-->
    <form method="post">
        <button type="submit" asp-page-handler="ActivationRelay" class="badge badge-secondary"
                id="btnActivationRelay">
            <!-- onClick="return greeting('Model.Guard.LastOrDefault().State')"> -->
            Реле-1

        </button>
    </form>
</div>
<!--тут код изменения цвета кнопок в зависимости от статуса-->
@if (Model.Guard.Count > 0) // проверим что массив не пустой
{
    if (Model.Guard[Model.Guard.Count - 1].State == false)
    {
<script>
    document.getElementById("btnActivationGuard").style.backgroundColor = "red";
    document.getElementById("btnActivationGuard").textContent="Охрана выключена";

</script>
    }
    else
    {
<script>
    document.getElementById("btnActivationGuard").style.backgroundColor = "green";
    document.getElementById("btnActivationGuard").textContent = "Охрана включена";
</script>
    }
    if (Model.Guard[Model.Guard.Count - 1].relay_1 == false)
    {
        <script>document.getElementById("btnActivationRelay").style.backgroundColor = "red";
            document.getElementById("btnActivationRelay").textContent = "Реле-1 выключено";

    </script>
    }
    else
    {
        <script>document.getElementById("btnActivationRelay").style.backgroundColor = "green";
            document.getElementById("btnActivationRelay").textContent = "Реле-1 включено";
    </script>
    }
}

<!--если не авторизован как админ, то кнопки не активны-->
@if (SignInManager.IsSignedIn(User) == false || User.IsInRole("Admin")!=true)
{
    <script>document.getElementById("btnActivationGuard").setAttribute("disabled", "disabled");</script>
    <script>document.getElementById("btnActivationRelay").setAttribute("disabled", "disabled");</script>
}

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GarageGuard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
    <script src="~/js/site.js"></script>
   
        ...
    <link rel="icon" href="/css/backgrnd/fav.svg" type="image/svg+xml">
        ...
    
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (m, e, t, r, i, k, a) {
            m[i] = m[i] || function () { (m[i].a = m[i].a || []).push(arguments) };
            m[i].l = 1 * new Date();
            for (var j = 0; j < document.scripts.length; j++) { if (document.scripts[j].src === r) { return; } }
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
            (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(93306456, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/93306456" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Guards/Index">GarageGuard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Guards/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GarageGuard - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>